from __future__ import annotations

class NativeWindowInfo:
    @property
    def id(self) -> int: ...
    @property
    def pid(self) -> int | None: ...
    @property
    def title(self) -> str: ...
    @property
    def app_name(self) -> str: ...
    @property
    def x(self) -> int | None: ...
    @property
    def y(self) -> int | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def is_minimized(self) -> bool | None: ...
    @property
    def is_maximized(self) -> bool | None: ...
    @property
    def is_focused(self) -> bool | None: ...

class NativeCapturer:
    def __init__(
        self,
        window_id: int,
        fps: int = ...,
        show_cursor: bool = ...,
        show_highlight: bool = ...,
        crop: tuple[int, int, int, int] | None = ...,
        output_resolution: str = ...,
    ) -> None: ...
    def next_frame(self) -> tuple[float, int, int, str, bytes] | None: ...
    def stop(self) -> None: ...
    @property
    def is_stopped(self) -> bool: ...
    @property
    def is_window_closed(self) -> bool: ...

def list_windows_native() -> list[NativeWindowInfo]: ...
def is_supported() -> bool: ...
def has_permission() -> bool: ...
def request_permission() -> bool: ...
def backend_name() -> str: ...
